spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    mapper-locations: classpath:/mapper/**/*.xml
#  redis:
#    host: localhost
#    port: 6379
#  session:
#    store-type: redis

server:
  port: 3000

jwt:
  header: Authorization
  secret: a2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbQ==
  access-token-validity-in-seconds: 1000 # 10 min
  refresh-token-validity-in-seconds: 60000 # 10 min
logging:
  level:
    root: debug

mybatis:
  con
