spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    mapper-locations: classpath:/mapper/**/*.xml
server:
  port: 3000

